[package]
name = "shinri-parser-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
shinri-core = { path = "../../shinri-core" }
shinri-parser = { path = ".." }

[[bin]]
name = "parse_script"
path = "fuzz_targets/parse_script.rs"
test = false
doc = false

[workspace]
